### ISSUE TITLE
Patch Question

### ISSUE THREAD

**Issue by MikeLud** [codeproject/CodeProject.AI-ObjectDetectionYOLOv8#2]
@ChrisMaunder I am making a YOLO11 module using this module as the templet. So far the module is running fine without the `fuse_lock` patch. What issue were you seeing that you had to add the `fuse_lock` patch. Also I tested the ObjectDetectionYOLOv8 module without the `fuse_lock` patch and it also runs fine.

One good thing is YOLO11 is backwards compatible with the YOLOv8 models

Thanks
Mike

**Comment by ChrisMaunder** [comment]
I *think* the issue is that fuse was being called multiple times such as between inferences (a bug that seems to have been fixed) and it was tripping over itself.

**Comment by MikeLud** [comment]
> I _think_ the issue is that fuse was being called multiple times such as between inferences (a bug that seems to have been fixed) and it was tripping over itself.

Thanks, I will add the `fuse_lock` patch in just to be safe.

**Comment by MikeLud** [comment]
Closed
